<h3>
	<?php echo $this->__("Twój wniosek został wysłany.") ?>
</h3>
<p>
	<?php echo $this->__("Dziękujemy za wypełnienie i wysłanie wniosku o kredyt na zakup towarów i usług Credit Agricole Bank Polska S.A. dla zamówienia nr %s", $this->getOrderId()) ?>
</p>
<p>
	<?php echo $this->__("Prosimy oczekiwać na kontakt telefoniczny lub pocztą elektroniczną z przedstawicielem Credit Agricole Bank Polska S.A..") ?>
	<?php echo $this->__("Informacje na temat statusu Twojego wniosku przekazywane będą bezpośrednio przez Credit Agricole Bank Polska S.A. oraz dostępne będą w sklepie %s", Mage::getStoreConfig("general/store_information/name")) ?>
</p>