<div id="service-calculate-installment">
    <?php if ($this->getImageType() == 'swf'): ?>
        <embed
            type="application/x-shockwave-flash"
            src="<?= $this->getImageUrl(); ?>"
            width="<?= $this->getImageWidth(); ?>"
            height="<?= $this->getImageHeight(); ?>"
            id="CAButton"
            name="CAButton"
            bgcolor="#ffffff"
            quality="high"
            wmode="transparent"
            flashvars="rata_url=<?= $this->getRateUrl() ?>?posId=<?= $this->getPSP(); ?>%26creditAmount=<?= $this->getCreditAmount(); ?>&amp;click_url=<?= $this->getClickUrl(); ?>?PARAM_PROFILE=<?= $this->getPSP(); ?>%26PARAM_TYPE=RAT%26PARAM_CREDIT_AMOUNT=<?= $this->getCreditAmount(); ?>"
        />
    <?php else: ?>
        <span>
            <a
                href="<?= $this->getClickUrl(); ?>?PARAM_PROFILE=<?= $this->getPSP(); ?>&PARAM_TYPE=RAT&PARAM_CREDIT_AMOUNT=<?= $this->getCreditAmount(); ?>"
                target="_blank"
            >
                <img
                    src="<?= $this->getImageUrl() ?>"
                    alt="<?= $this->__("Oblicz wysokość raty") ?>"
                    border="0"
                />
            </a>
        </span>
    <?php endif ?>
</div>
